language: node_js
node_js:
  - 13
  - 14
  - 15
os:
  - linux
  - windows
arch:
  - amd64
  - arm64
compiler: gcc
before_install:
- if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update -qq; fi;
- curl https://sh.rustup.rs -sSf | sh -s -- -y
- export PATH="$HOME/node_modules/.bin/:$HOME/node_modules/node-pre-gyp/bin/:./node_modules/node-pre-gyp/bin:$HOME/.cargo/bin:$PATH"
- if [ $TRAVIS_OS_NAME = linux ]; then source "$HOME/.cargo/env"; fi;
- if [ $TRAVIS_OS_NAME = windows ]; then rustup toolchain install stable-x86_64-pc-windows-msvc; fi;
- if [ $TRAVIS_OS_NAME = windows ]; then rustup default stable-x86_64-pc-windows-msvc; fi;
- npm install neon-cli -g
- npm install node-pre-gyp@amilajack/node-pre-gyp#neon-compat node-pre-gyp-github
- PUBLISH_BINARY=true
- if [[ "$TRAVIS_TAG" == "" ]]; then PUBLISH_BINARY=false; fi;
- echo "Publish binary = $PUBLISH_BINARY"
install:
- travis_wait 45 neon build --release
before_script:
- if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp package; fi;
- if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp-github publish --release; fi;
after_success:
- node-pre-gyp-github info
deploy:
  provider: npm
  on:
    tags: true
    condition: "( $TRAVIS_CPU_ARCH = amd64 ) && ( $TRAVIS_OS_NAME = linux )"
  email: fastjack79@yahoo.com
  api_key:
    secure: hMghHshpU5Ax/99ynonYPF9E9RWAbPUGJJihTVCMXr4WsvRzKh2aH6lfiPcT+90OBGZ44ICudBkYe7rk2qMbg3GdcfKgmSlQB78qQWiXw4MwN1LYopoUkECGnULr8GNYWB+Lfnj9hZ2StpcKG0yGp+FV/99OnmRUa4HKNEs2jBDhyB732IfMV1GFyYhOD5+Ty6yW0HogEO9y8rwPuWmj6OtrMfryTklI77j9QSFXKBwmyUsBohQxCbRiN7vpYgM/JXA/X50I+fQrzxxLaBZ5iNENOQp90NgOMA525c/w45uiI+1yXeYRBBZkNL/MU2D8B9HXJfk5/6WCER/T0WHdoayrW9QJw9mDhSi8d00Q8X0KDS2IrisaUK066eYtlvslsRKtxisCtk21okW6NekcqEzgwRt18N7CG+FNq49nVzfFCU2npi9jszxxePskHC+VMLat4NYJ7sKJiyxkkRvNyrDU0jknw36AxyQu2cZb5WRkAnQUBVJUx8IZO9FnjjV2veblUWIlKsud1Ice+3ev1yWiurgcKCZ0j6ukOWMOTA62Ys6UtaXKZTYjanS0FkqW3qBN4uMVIDlweQrL0yKKSDxtneOtJO1dqvO17zAbEErwkr5W2u98qfW+S9gxgmoaPSIlLeuR4tkmCXglpF9V/TlE8CuhHMLbmNJLFrE3KqQ=
